[RXTEAM-4748] Remove unused mentions, references,  cleaned [EOF] tags and compacted deeplink page
Prescrypto/prescrypto-docs pull request #30
Opened 2022-04-07 22:25 UTC by JasonBerto

inicially we removed the clinic mention, and 
cleaned [EOF] tags

2022-04-07 22:35 UTC, ebarojas commented
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/8750702/162330659-313ca2d0-b379-4dda-aec3-cf15ff6679fa.png">

2022-04-07 22:37 UTC, ebarojas requested changes
EOFs should stay.

2022-04-07 22:38 UTC, ebarojas commented on docs/changelog/overview.md
> +- (7 Apr, 2022) Removed unused parmateres mentions and references, cleaned some typos and compacted info from different pages into the same related ones.
👍

2022-04-07 22:38 UTC, ebarojas commented on docs/deeplink/deeplink.md
> +With this type of integration the Medic user will access Prescrypto through a "Deeplink", an URL filled with special parameters that will log automatically the user on the platform and can pre-fill c
👍

2022-04-07 22:38 UTC, ebarojas commented on docs/intro.md
> +## Free Text Medications
Muy bien quitar lo de Basic Drugs!

2022-04-08 17:02 UTC, JasonBerto commented
Se volvió añadir lo de [EOF] en todos los archivos de narkdown de la documentacion

2022-04-08 17:18 UTC, ebarojas commented
> Se volvió añadir lo de [EOF] en todos los archivos de narkdown de la documentacion

Lo reviso en la tarde, pero estos cambios se ven :godmode:

2022-04-11 13:53 UTC, xtornasol512 approved these changes
LGTM! But please change the base branch "main" to "develop" @JasonBerto

2022-04-12 22:27 UTC, ebarojas approved these changes
🚀

2022-04-12 22:27 UTC, ebarojas commented on docs/deeplink/deeplink.md
> +**IMPORTANT NOTE: All the param values have to be URI ENCODED, otherwise, the link could not work as expected**
:+1:

2022-04-12 22:27 UTC, ebarojas commented on docs/intro.md
> -## Difference between Basic Drugs and Free Medications
👍

2022-04-12 22:30 UTC, ebarojas commented
Buenísimo upgrade @JasonBerto 

Va para arriba, sólo dos cosas:
1. Me quedó duda (para fix a futuro) acá:
<img width="965" alt="image" src="https://user-images.githubusercontent.com/8750702/163065196-de3dc6d3-d271-481b-90b2-f8181da1f7fc.png">
2. El PR debería ser hacia ```develop```

2022-04-12 22:30 UTC, merged