update webhook doc
Prescrypto/prescrypto-docs pull request #42
Opened 2024-09-06 14:33 UTC by xtornasol512

## Description

Update webhook documentation

## Changes

- Update webhook docs
- Add Get Prescription endpoint
- Add ref to Patient Landing and Get Rx doc

2024-09-20 19:38 UTC, ebarojas requested changes
@xtornasol512 ¿Cómo se agrega un webhook?

Esta es la parte más importante que falta. Documentar cómo se agrega un webhook-
- como configuración de los miembres de un Hospital
- Con una campaña ATM en qué campo
- hay otro modo? especificado por médico?

2024-09-21 00:50 UTC, xtornasol512 commented
> @xtornasol512 ¿Cómo se agrega un webhook?
> 
> Esta es la parte más importante que falta. Documentar cómo se agrega un webhook-
> 
> * como configuración de los miembres de un Hospital
> * Con una campaña ATM en qué campo
> * hay otro modo? especificado por médico?

Nuevos cambios en la doc:

Se agrego como crear, añadir webhooks de forma convencional.
Se agrego como usar los promo code, y pedirlos antes a un admin.
Se agrego detalles del limite del endpoint de medics

2024-09-21 01:40 UTC, ebarojas approved these changes
Cool, mucho mejor.

🚀

2024-09-21 01:40 UTC, ebarojas commented on docs/api/medic.md
> +The maximum limit for the MEDIC LIST endpoint is 100 records per request. If you request more than 100 items, only the first 100 records will be returned. However, this doesn’t mean you can’t retriev
👍

2024-09-21 01:41 UTC, merged